# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_contact_date_of_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='delay_in_days',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
