# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_contact_functional_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
