# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20170705_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
