# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20170705_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='language_preference',
            field=models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi'), ('GUJ', 'Gujarati')], default='ENG', max_length=4),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='script_selection',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
