# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_contact_telerivet_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='012345', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9199999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
