# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_contact_alt_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Contact')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
