# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_visitdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('direction', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 20, 44, 42, 74833, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_heard_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 20, 44, 42, 74753, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='message',
            name='contacts',
            field=models.ManyToManyField(to='management.Contact'),
        ),
    ]
