# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20170707_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_heard_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
