# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_remove_contact_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='telerivet_time_created',
            new_name='time_created',
        ),
        migrations.AlterField(
            model_name='contact',
            name='language_preference',
            field=models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi'), ('GUJ', 'Gujarati')], default='ENG', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_heard_from',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url_information',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
