# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20170718_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitdate',
            name='contact',
        ),
        migrations.DeleteModel(
            name='VisitDate',
        ),
    ]
