# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20170724_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
