# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20170818_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='trial_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='trial_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
