# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_message_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_heard_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
