language: python

python:
  - 2.7
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=cshsms.settings
  - export PYTHONPATH=/home/travis/build/charityscience/csh-sms
  - export IS_TRAVIS=true
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install codecov
  - mkdir logs
  - touch logs/cshsms.log

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - psql -c "ALTER ROLE travis WITH LOGIN;" -U postgres
  - psql -c "ALTER ROLE travis WITH CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE travisdb TO travis;" -U postgres

script:
  - python manage.py migrate
  - coverage run manage.py test
 
after_success:
  - codecov


