language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=cshsms.settings
  - export PYTHONPATH=/home/travis/build/charityscience/csh-sms
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - python manage.py test

notifications:
  email:
    on_success: change
    on_failure: always
